version: '3.4'
services:
  bucstop:
    image: $(DOCKER-REPO-PATH)/bucstop
    environment:
      - micro=http://micro
      #- ASPNETCORE_URLS=https://+;http://+;
      #- ASPNETCORE_HTTPS_PORT=443
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=$(CERT-PASS)
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
    #volumes:
    #  - /home/ubuntu:/https/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - micro
    restart: unless-stopped
  micro:
    image: $(DOCKER-REPO-PATH)/gamemicro
    restart: unless-stopped
